version: '3'

# Still need to work in configuration and set up redis
services:
  db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/core
    ports:
      - "8000:8000"
    depends_on:
      - db
