# Generated by Django 2.1.1 on 2018-09-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Journey', max_length=128)),
                ('type', models.IntegerField(choices=[(1, 'Health'), (2, 'Finance'), (3, 'Skill development')])),
                ('status', models.IntegerField(choices=[(1, 'Preliminary'), (2, 'Scheduled'), (3, 'Active'), (4, 'Finished'), (5, 'Overdue'), (6, 'Quit')])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Roadmap', max_length=128)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Task', max_length=128)),
                ('status', models.IntegerField(choices=[(1, 'Preliminary'), (2, 'Scheduled'), (3, 'Active'), (4, 'Finished'), (5, 'Overdue'), (6, 'Quit'), (7, 'Hold')])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.Journey')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('email_address', models.EmailField(max_length=254)),
                ('dob', models.DateField(max_length=8)),
                ('country_code', models.IntegerField(default=52)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='journey',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journeys', to='core.RoadMap'),
        ),
    ]
