# Generated by Django 2.1.1 on 2018-09-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('email_address', models.EmailField(max_length=254)),
                ('dob', models.DateField(max_length=8)),
                ('country_code', models.IntegerField(default=52)),
                ('last_login', models.DateField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
