# Generated by Django 2.1.1 on 2018-09-24 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Journey', max_length=128)),
                ('type', models.IntegerField(choices=[(1, 'Health'), (2, 'Finance'), (3, 'Skill development')])),
                ('status', models.IntegerField(choices=[(1, 'Preliminary'), (2, 'Scheduled'), (3, 'Skill development'), (4, 'Active'), (5, 'Finished'), (6, 'Overdue'), (7, 'Quit')])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journeys', to='core.RoadMap')),
            ],
        ),
    ]
